/**
 * Self-host tiny font subsets containing only the glyphs this page actually uses.
 * Re-run (`npm run fonts`) whenever the copy changes.
 */
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

// `only` limits a family to its own accent glyphs — brush faces are heavy per glyph.
const FAMILIES = [
  { family: 'Noto Serif SC' },
  { family: 'ZCOOL XiaoWei' },
  { family: 'Ma Shan Zheng', only: '鸳鸯卷一二三渡野灯烬' },
]
const OUT = 'public/fonts'
// Chrome UA is what makes the API hand back woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'

async function sourceFiles(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await sourceFiles(path)))
    else if (/\.(tsx?|html)$/.test(entry.name)) out.push(path)
  }
  return out
}

const files = [...(await sourceFiles('src')), 'index.html']
const text = (await Promise.all(files.map((f) => readFile(f, 'utf8')))).join('')

// Every CJK ideograph, CJK punctuation and ASCII printable found in the source.
const glyphs = new Set(
  text.match(/[　-〿一-鿿＀-￯ -~]/g) ?? [],
)
const chars = [...glyphs].sort().join('')
console.log(`${chars.length} unique glyphs from ${files.length} files`)

await mkdir(OUT, { recursive: true })
const faces = []

for (const { family, only } of FAMILIES) {
  const url =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@400` +
    `&text=${encodeURIComponent(only ?? chars)}&display=swap`
  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`${family}: ${r.status} ${r.statusText}`)
    return r.text()
  })

  const woff2 = css.match(/url\((https:\/\/[^)]+)\)\s*format\('woff2'\)/)?.[1]
  if (!woff2) throw new Error(`${family}: no woff2 in response`)

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}.woff2`
  const body = Buffer.from(await fetch(woff2).then((r) => r.arrayBuffer()))
  await writeFile(join(OUT, file), body)
  console.log(`  ${file}  ${(body.length / 1024).toFixed(1)} KB`)

  faces.push(
    `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: 400;\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      `}`,
  )
}

await writeFile(
  join(OUT, 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n${faces.join('\n')}\n`,
)
console.log(`wrote ${OUT}/fonts.css`)
